name: 'Monorepo Split With Tag'

on:
    push:
        branches:
            - master

jobs:
    monorepo_split_test_with_tag:
        runs-on: ubuntu-latest

        steps:
              - name: Checkout code
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            # see https://github.com/WyriHaximus/github-action-get-previous-tag
              - name: Previous tag
                id: previous_tag
                uses: "WyriHaximus/github-action-get-previous-tag@master"

              - name: Decrypt secrets
                uses: zgosalvez/github-actions-decrypt-secrets@v1
                with:
                    secrets_file: .github/workflows/secrets.json.gpg
                    map: 'USER_PASSWORD=PASSWORD'
                env:
                    GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

              - name: Split
                uses: "wp-next/wp-next@master"
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    # ↓ split "packages/easy-coding-standard" directory
                    package-directory: 'packages/View'

                    # ↓ into https://github.com/symplify/easy-coding-standard repository
                    split-repository-organization: 'wp-next'
                    split-repository-name: 'view'

                    tag: ${{ steps.previous_tag.outputs.tag }}
                    user-email: 'kimla89@gmail.com'
                    user-name: 'Kimla'
                    user-password: ${{ secrets.GPG_PASSPHRASE }}